// Atoms are small parts of the applications. It is where you put buttons,icons, etc
export { default as Profile_button } from "./profile-button";
export { default as Heart_button } from "./heart-icon";
export { default as Chat_button } from "./chat-icon";
export { default as Match_button } from "./matching-icon";
export { default as Flip_button } from "./flip-icon";
export { default as Remove_button } from "./remove-button";
export { default as AppTitle } from "./app-title";
export { default as Button } from "./button";
export { default as TermsButton } from "./termsBtn";
export { default as PrivacyButton } from "./privacyBtn";
export { default as ContinueButton } from "./continueButton";
export { default as OnboardingTitle } from "./onboarding-page-title";
export { default as NumberEntry } from "./number-entry";
export { default as InfoText } from "./info-text";
export { default as AssistButton } from "./assist-button";
export { default as InputResponse } from "./input-response";
export { default as InvertedLogo } from "./inverted-logo";
export { default as LargePhotoInput } from "./large-photo-input";
export { default as MediumPhotoInput } from "./medium-photo-input";
export { default as SmallPhotoInput } from "./small-photo-input";
export { default as PromptInputBox } from "./prompt-input-box";
export { default as AddAPrompt } from "./add-a-prompt";
export { default as PromptOptions } from "./prompt-option";
export { default as PromptTitle } from "./prompt-title";
export { default as SubTitle } from "./sub-title";
export { default as SettingsButtonTitle } from "./settings-button-title";
export {default as Add_photo_button} from "./add-photo-button";